stages:
  - build
variables:
  DOCKER_IMAGE_NAME: $CI_PROJECT_NAME
  DOCKERHUB_PASSWORD: "unset"
  DOCKERHUB_USERNAME: "unset"

image: docker:latest

services:
  - docker:dind

variables:
  TAG_COMMIT: $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
  TAG_LATEST: $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest

build tag:
  stage: build
  only:
    - tags
  script:
    - echo "Building ${TAG_COMMIT}..."
    - docker pull $TAG_LATEST || true
    - docker build -t ${TAG_COMMIT} .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker push ${TAG_COMMIT}

build latest:
  stage: build
  only:
    refs:
      - main
      - master
  script:
    - echo "Building ${TAG_LATEST}..."
    - docker pull $TAG_LATEST || true
    - docker build -t ${TAG_LATEST} .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker push ${TAG_LATEST}
   
