stages:
  - build
variables:

image: docker:latest

services:
  - docker:dind

# You must also have a DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD in your ci variables
variables:
  TAG_COMMIT: $DOCKERHUB_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  TAG_LATEST: $DOCKERHUB_USERNAME/$CI_PROJECT_NAME:latest

build tag:
  stage: build
  only:
    - tags
  script:
    - echo "Building ${TAG_COMMIT}..."
    - docker pull $TAG_LATEST || true
    - docker build -t ${TAG_COMMIT} .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker push ${TAG_COMMIT}

build latest:
  stage: build
  only:
    refs:
      - main
      - master
  script:
    - echo "Building ${TAG_LATEST}..."
    - docker pull $TAG_LATEST || true
    - docker build -t ${TAG_LATEST} .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker push ${TAG_LATEST}
   
